version: "3"
services:
  openresty:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro #将外边时间直接挂载到容器内部，权限只读
      - /etc/timezone:/etc/timezone:ro #将外面的时间挂载到容器内部，权限只读，容器内不可修改
      - ./nginx.conf:/root/nginx/nginx.conf
      - ./conf:/root/nginx/conf
      - ./logs:/root/nginx/logs
      - ./lua:/root/nginx/lua:rw
    environment:
      - REDIS_HOST=10.96.65.24
      - REDIS_PORT=6363
      - REDIS_PASS=12345678
      - REDIS_IPBLACK_KEY=ngx_ipblack_list
    ports:
      - "9581:80"
    command: bash -c "/usr/local/openresty/nginx/sbin/nginx -p `pwd`/ -c nginx.conf -g 'daemon off;'"
    tty: true
    container_name: openresty