version: "3"
services:
  redis-node-1:
    container_name: redis-node-1
    image: redis:latest
    ports:
      - "6361:6361"
      - "16361:16361"
    networks:
      testNetwork:
        ipv4_address: 192.18.0.2

    volumes:
      - ./node-1/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./node-1/data:/data:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

  redis-node-2:
    container_name: redis-node-2
    image: redis:latest
    ports:
      - "6362:6362"
      - "16362:16362"
    networks:
      testNetwork:
        ipv4_address: 192.18.0.3
    volumes:
      - ./node-2/redis.conf:/usr/local/etc/redis/redis.conf
      - ./node-2/data:/data:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

  redis-node-3:
    container_name: redis-node-3
    image: redis:latest
    ports:
      - "6363:6363"
      - "16363:16363"
    networks:
      testNetwork:
        ipv4_address: 192.18.0.4
    volumes:
      - ./node-3/redis.conf:/usr/local/etc/redis/redis.conf
      - ./node-3/data:/data:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

  redis-node-4:
    container_name: redis-node-4
    image: redis:latest
    ports:
      - "6364:6364"
      - "16364:16364"
    networks:
      testNetwork:
        ipv4_address: 192.18.0.5
    volumes:
      - ./node-4/redis.conf:/usr/local/etc/redis/redis.conf
      - ./node-4/data:/data:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

  redis-node-5:
    container_name: redis-node-5
    image: redis:latest
    ports:
      - "6365:6365"
      - "16365:16365"
    networks:
      testNetwork:
        ipv4_address: 192.18.0.6
    volumes:
      - ./node-5/redis.conf:/usr/local/etc/redis/redis.conf
      - ./node-5/data:/data:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"

  redis-node-6:
    container_name: redis-node-6
    image: redis:latest
    ports:
      - "6366:6366"
      - "16366:16366"
    networks:
      testNetwork:
        ipv4_address: 192.18.0.7
    volumes:
      - ./node-6/redis.conf:/usr/local/etc/redis/redis.conf
      - ./node-6/data:/data:rw
    environment:
      - TZ=Asia/Shanghai
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
networks:
  testNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.0.0/16